<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="WeatherForecast.fs"/>
        <Compile Include="Controllers/WeatherForecastController.fs"/>
        <Compile Include="Program.fs"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="Samples.http" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Marmotte\Marmotte.fsproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />
      <PackageReference Include="Scalar.AspNetCore" Version="2.0.29" />
    </ItemGroup>

</Project>
